### ISSUE TITLE
Hide or add disabled class when on iOS / non-flash browser

### ISSUE THREAD

**Issue by DJM0** [jasonkriss/ember-zeroclipboard#1]
Would it be possible to add this in as there is currently no feedback that the copy didn't work in browsers without flash?

**Comment by jasonkriss** [comment]
@davidmaitland I wouldn't want to have this addon making too many ui decisions but i think adding a class seems like a great idea. I likely won't have time to tackle this any time soon so if you'd be willing, a PR would be greatly appreciated.

Regardless, thanks for bringing this up. Some relevant discussion [here](https://github.com/zeroclipboard/zeroclipboard/issues/552) and [here](https://github.com/twbs/bootstrap/commit/229e88892913d5c8b712510c28b78bfa114596e5).

**Comment by DJM0** [comment]
Fully agree. Will see if I get time to look at this over the weekend!

**Comment by jasonkriss** [comment]
Sounds great. Thanks!
