### ISSUE TITLE
app[initializerType] is not a function

### ISSUE THREAD

**Issue by arunrajasankar** [jasonkriss/ember-zeroclipboard#3]
Uncaught TypeError: app[initializerType] is not a function

the above error occurs when i install ember-zeroclipboard and start ember server

My ember version is 1.11.1
and Ember Data : 1.0.0-beta.16.1

**Comment by jasonkriss** [comment]
Sorry about that @arunrajasankar. This addon actually requires at least Ember 1.12 (it uses an instance initializer). There should have been a mention in the README. I added one now. Again, sorry about that!

**Comment by arunrajasankar** [comment]
Ok thanks a lot! for the reply
